{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "base.secretName" (dict "secretName" $name "context" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
type: {{ $secret.type | default "Opaque" }}
{{- if $secret.data }}
data:
  {{- toYaml $secret.data | nindent 2 }}
{{- end }}
{{- if $secret.stringData }}
stringData:
  {{- toYaml $secret.stringData | nindent 2 }}
{{- end }}
{{- end }}
